config/routes.rb
HealthTracker::Application.routes.draw do
  resources :alcohols

  resources :caffeines

  resources :vitamins

  resources :foods

  resources :sleeps

  resources :gyms

  match '/pages/gym' => 'pages#gym'
  match '/pages/sleep' => 'pages#sleep'
  match '/pages/vitamins' => 'pages#vitamins'
  match '/pages/caffeine' => 'pages#caffeine'
  match '/pages/alcohol' => 'pages#alcohol'

  root :to => 'pages#index'

end

app/models/vitamin.rb
class Vitamin < ActiveRecord::Base
end

app/controllers/vitamins_controller.rb
class VitaminsController < ApplicationController
  # GET /vitamins
  # GET /vitamins.json
  def index
    @vitamins = Vitamin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vitamins }
    end
  end

  # GET /vitamins/1
  # GET /vitamins/1.json
  def show
    @vitamin = Vitamin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vitamin }
    end
  end

  # GET /vitamins/new
  # GET /vitamins/new.json
  def new
    @vitamin = Vitamin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vitamin }
    end
  end

  # GET /vitamins/1/edit
  def edit
    @vitamin = Vitamin.find(params[:id])
  end

  # POST /vitamins
  # POST /vitamins.json
  def create
    @vitamin = Vitamin.new(params[:vitamin])

    respond_to do |format|
      if @vitamin.save
        format.html { redirect_to @vitamin, notice: 'Vitamin was successfully created.' }
        format.json { render json: @vitamin, status: :created, location: @vitamin }
      else
        format.html { render action: "new" }
        format.json { render json: @vitamin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vitamins/1
  # PUT /vitamins/1.json
  def update
    @vitamin = Vitamin.find(params[:id])

    respond_to do |format|
      if @vitamin.update_attributes(params[:vitamin])
        format.html { redirect_to @vitamin, notice: 'Vitamin was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @vitamin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vitamins/1
  # DELETE /vitamins/1.json
  def destroy
    @vitamin = Vitamin.find(params[:id])
    @vitamin.destroy

    respond_to do |format|
      format.html { redirect_to vitamins_url }
      format.json { head :ok }
    end
  end
end

app/helpers/vitamins_helper.rb
module VitaminsHelper
end

app/views/vitamins/_form.html.erb
<%= form_for(@vitamin) do |f| %>
  <% if @vitamin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vitamin.errors.count, "error") %> prohibited this vitamin from being saved:</h2>

      <ul>
      <% @vitamin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vitamins/edit.html.erb
<h1>Editing vitamin</h1>

<%= render 'form' %>

<%= link_to 'Show', @vitamin %> |
<%= link_to 'Back', vitamins_path %>

app/views/vitamins/index.html.erb
<h1>Listing vitamins</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vitamins.each do |vitamin| %>
  <tr>
    <td><%= link_to 'Show', vitamin %></td>
    <td><%= link_to 'Edit', edit_vitamin_path(vitamin) %></td>
    <td><%= link_to 'Destroy', vitamin, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vitamin', new_vitamin_path %>

app/views/vitamins/new.html.erb
<h1>New vitamin</h1>

<%= render 'form' %>

<%= link_to 'Back', vitamins_path %>

app/views/vitamins/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_vitamin_path(@vitamin) %> |
<%= link_to 'Back', vitamins_path %>