config/routes.rb
HealthTracker::Application.routes.draw do
  resources :alcohols

  resources :caffeines

  resources :vitamins

  resources :foods

  resources :sleeps

  resources :gyms

  match '/pages/gym' => 'pages#gym'
  match '/pages/sleep' => 'pages#sleep'
  match '/pages/vitamins' => 'pages#vitamins'
  match '/pages/caffeine' => 'pages#caffeine'
  match '/pages/alcohol' => 'pages#alcohol'

  root :to => 'pages#index'

end

app/models/sleep.rb
class Sleep < ActiveRecord::Base
end

app/controllers/sleeps_controller.rb
class SleepsController < ApplicationController
  # GET /sleeps
  # GET /sleeps.json
  def index
    @sleeps = Sleep.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sleeps }
    end
  end

  # GET /sleeps/1
  # GET /sleeps/1.json
  def show
    @sleep = Sleep.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sleep }
    end
  end

  # GET /sleeps/new
  # GET /sleeps/new.json
  def new
    @sleep = Sleep.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sleep }
    end
  end

  # GET /sleeps/1/edit
  def edit
    @sleep = Sleep.find(params[:id])
  end

  # POST /sleeps
  # POST /sleeps.json
  def create
    @sleep = Sleep.new(params[:sleep])

    respond_to do |format|
      if @sleep.save
        format.html { redirect_to @sleep, notice: 'Sleep was successfully created.' }
        format.json { render json: @sleep, status: :created, location: @sleep }
      else
        format.html { render action: "new" }
        format.json { render json: @sleep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sleeps/1
  # PUT /sleeps/1.json
  def update
    @sleep = Sleep.find(params[:id])

    respond_to do |format|
      if @sleep.update_attributes(params[:sleep])
        format.html { redirect_to @sleep, notice: 'Sleep was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @sleep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sleeps/1
  # DELETE /sleeps/1.json
  def destroy
    @sleep = Sleep.find(params[:id])
    @sleep.destroy

    respond_to do |format|
      format.html { redirect_to sleeps_url }
      format.json { head :ok }
    end
  end
end

app/helpers/sleeps_helper.rb
module SleepsHelper
end

app/views/sleeps/_form.html.erb
<%= form_for(@sleep) do |f| %>
  <% if @sleep.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sleep.errors.count, "error") %> prohibited this sleep from being saved:</h2>

      <ul>
      <% @sleep.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sleeps/edit.html.erb
<h1>Editing sleep</h1>

<%= render 'form' %>

<%= link_to 'Show', @sleep %> |
<%= link_to 'Back', sleeps_path %>

app/views/sleeps/index.html.erb
<h1>Listing sleeps</h1>

<table>
  <tr>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sleeps.each do |sleep| %>
  <tr>
    <td><%= sleep.notes %></td>
    <td><%= link_to 'Show', sleep %></td>
    <td><%= link_to 'Edit', edit_sleep_path(sleep) %></td>
    <td><%= link_to 'Destroy', sleep, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sleep', new_sleep_path %>

app/views/sleeps/new.html.erb
<h1>New sleep</h1>

<%= render 'form' %>

<%= link_to 'Back', sleeps_path %>

app/views/sleeps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Notes:</b>
  <%= @sleep.notes %>
</p>


<%= link_to 'Edit', edit_sleep_path(@sleep) %> |
<%= link_to 'Back', sleeps_path %>