config/routes.rb
HealthTracker::Application.routes.draw do
  resources :alcohols

  resources :caffeines

  resources :vitamins

  resources :foods

  resources :sleeps

  resources :gyms

  match '/pages/gym' => 'pages#gym'
  match '/pages/sleep' => 'pages#sleep'
  match '/pages/vitamins' => 'pages#vitamins'
  match '/pages/caffeine' => 'pages#caffeine'
  match '/pages/alcohol' => 'pages#alcohol'

  root :to => 'pages#index'

end

app/models/caffeine.rb
class Caffeine < ActiveRecord::Base
end

app/controllers/caffeines_controller.rb
class CaffeinesController < ApplicationController
  # GET /caffeines
  # GET /caffeines.json
  def index
    @caffeines = Caffeine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @caffeines }
    end
  end

  # GET /caffeines/1
  # GET /caffeines/1.json
  def show
    @caffeine = Caffeine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @caffeine }
    end
  end

  # GET /caffeines/new
  # GET /caffeines/new.json
  def new
    @caffeine = Caffeine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @caffeine }
    end
  end

  # GET /caffeines/1/edit
  def edit
    @caffeine = Caffeine.find(params[:id])
  end

  # POST /caffeines
  # POST /caffeines.json
  def create
    @caffeine = Caffeine.new(params[:caffeine])

    respond_to do |format|
      if @caffeine.save
        format.html { redirect_to @caffeine, notice: 'Caffeine was successfully created.' }
        format.json { render json: @caffeine, status: :created, location: @caffeine }
      else
        format.html { render action: "new" }
        format.json { render json: @caffeine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /caffeines/1
  # PUT /caffeines/1.json
  def update
    @caffeine = Caffeine.find(params[:id])

    respond_to do |format|
      if @caffeine.update_attributes(params[:caffeine])
        format.html { redirect_to @caffeine, notice: 'Caffeine was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @caffeine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caffeines/1
  # DELETE /caffeines/1.json
  def destroy
    @caffeine = Caffeine.find(params[:id])
    @caffeine.destroy

    respond_to do |format|
      format.html { redirect_to caffeines_url }
      format.json { head :ok }
    end
  end
end

app/helpers/caffeines_helper.rb
module CaffeinesHelper
end

app/views/caffeines/_form.html.erb
<%= form_for(@caffeine) do |f| %>
  <% if @caffeine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@caffeine.errors.count, "error") %> prohibited this caffeine from being saved:</h2>

      <ul>
      <% @caffeine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/caffeines/edit.html.erb
<h1>Editing caffeine</h1>

<%= render 'form' %>

<%= link_to 'Show', @caffeine %> |
<%= link_to 'Back', caffeines_path %>

app/views/caffeines/index.html.erb
<h1>Listing caffeines</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @caffeines.each do |caffeine| %>
  <tr>
    <td><%= link_to 'Show', caffeine %></td>
    <td><%= link_to 'Edit', edit_caffeine_path(caffeine) %></td>
    <td><%= link_to 'Destroy', caffeine, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Caffeine', new_caffeine_path %>

app/views/caffeines/new.html.erb
<h1>New caffeine</h1>

<%= render 'form' %>

<%= link_to 'Back', caffeines_path %>

app/views/caffeines/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_caffeine_path(@caffeine) %> |
<%= link_to 'Back', caffeines_path %>