config/routes.rb
HealthTracker::Application.routes.draw do
  resources :alcohols

  resources :caffeines

  resources :vitamins

  resources :foods

  resources :sleeps

  resources :gyms

  match '/pages/gym' => 'pages#gym'
  match '/pages/sleep' => 'pages#sleep'
  match '/pages/vitamins' => 'pages#vitamins'
  match '/pages/caffeine' => 'pages#caffeine'
  match '/pages/alcohol' => 'pages#alcohol'

  root :to => 'pages#index'

end

app/models/alcohol.rb
class Alcohol < ActiveRecord::Base
end

app/controllers/alcohols_controller.rb
class AlcoholsController < ApplicationController
  # GET /alcohols
  # GET /alcohols.json
  def index
    @alcohols = Alcohol.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alcohols }
    end
  end

  # GET /alcohols/1
  # GET /alcohols/1.json
  def show
    @alcohol = Alcohol.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @alcohol }
    end
  end

  # GET /alcohols/new
  # GET /alcohols/new.json
  def new
    @alcohol = Alcohol.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @alcohol }
    end
  end

  # GET /alcohols/1/edit
  def edit
    @alcohol = Alcohol.find(params[:id])
  end

  # POST /alcohols
  # POST /alcohols.json
  def create
    @alcohol = Alcohol.new(params[:alcohol])

    respond_to do |format|
      if @alcohol.save
        format.html { redirect_to @alcohol, notice: 'Alcohol was successfully created.' }
        format.json { render json: @alcohol, status: :created, location: @alcohol }
      else
        format.html { render action: "new" }
        format.json { render json: @alcohol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /alcohols/1
  # PUT /alcohols/1.json
  def update
    @alcohol = Alcohol.find(params[:id])

    respond_to do |format|
      if @alcohol.update_attributes(params[:alcohol])
        format.html { redirect_to @alcohol, notice: 'Alcohol was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @alcohol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alcohols/1
  # DELETE /alcohols/1.json
  def destroy
    @alcohol = Alcohol.find(params[:id])
    @alcohol.destroy

    respond_to do |format|
      format.html { redirect_to alcohols_url }
      format.json { head :ok }
    end
  end
end

app/helpers/alcohols_helper.rb
module AlcoholsHelper
end

app/views/alcohols/_form.html.erb
<%= form_for(@alcohol) do |f| %>
  <% if @alcohol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alcohol.errors.count, "error") %> prohibited this alcohol from being saved:</h2>

      <ul>
      <% @alcohol.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alcohols/edit.html.erb
<h1>Editing alcohol</h1>

<%= render 'form' %>

<%= link_to 'Show', @alcohol %> |
<%= link_to 'Back', alcohols_path %>

app/views/alcohols/index.html.erb
<h1>Listing alcohols</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @alcohols.each do |alcohol| %>
  <tr>
    <td><%= link_to 'Show', alcohol %></td>
    <td><%= link_to 'Edit', edit_alcohol_path(alcohol) %></td>
    <td><%= link_to 'Destroy', alcohol, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Alcohol', new_alcohol_path %>

app/views/alcohols/new.html.erb
<h1>New alcohol</h1>

<%= render 'form' %>

<%= link_to 'Back', alcohols_path %>

app/views/alcohols/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_alcohol_path(@alcohol) %> |
<%= link_to 'Back', alcohols_path %>